// Code generated by bevegen. DO NOT EDIT.

package main

import (
	"github.com/beve-org/beve-go/core"
)

// MarshalBEVE encodes Product to BEVE format using generated code.
//
// This method is automatically generated by bevegen and provides
// significantly better performance than reflection-based encoding.
//
// Performance: ~100ns for small structs (vs ~1000ns with reflection)
func (s *Product) MarshalBEVE() ([]byte, error) {
	enc := core.GetEncoderFromPool()
	defer core.PutEncoderToPool(enc)

	// Write struct header (TYPE_OBJECT)
	if err := enc.WriteByte(0x86); err != nil {
		return nil, err
	}

	// Write field count (placeholder, will be updated)
	fieldCount := 6
	// Skip description if zero
	if s.Description == "" {
		fieldCount--
	}

	if err := enc.WriteCompressedUint(uint64(fieldCount)); err != nil {
		return nil, err
	}

	// Encode fields
	// Field: id
	if err := core.EncodeStringFast(enc, "id"); err != nil {
		return nil, err
	}
	if err := core.EncodeIntFast(enc, int64(s.ID)); err != nil {
		return nil, err
	}
	// Field: name
	if err := core.EncodeStringFast(enc, "name"); err != nil {
		return nil, err
	}
	if err := core.EncodeStringFast(enc, s.Name); err != nil {
		return nil, err
	}
	if s.Description != "" {
		// Field: description
		if err := core.EncodeStringFast(enc, "description"); err != nil {
			return nil, err
		}
		if err := core.EncodeStringFast(enc, s.Description); err != nil {
			return nil, err
		}
	}
	// Field: price
	if err := core.EncodeStringFast(enc, "price"); err != nil {
		return nil, err
	}
	if err := core.EncodeFloat64Fast(enc, s.Price); err != nil {
		return nil, err
	}
	// Field: in_stock
	if err := core.EncodeStringFast(enc, "in_stock"); err != nil {
		return nil, err
	}
	if err := core.EncodeBoolFast(enc, s.InStock); err != nil {
		return nil, err
	}
	// Field: quantity
	if err := core.EncodeStringFast(enc, "quantity"); err != nil {
		return nil, err
	}
	if err := core.EncodeIntFast(enc, int64(s.Quantity)); err != nil {
		return nil, err
	}

	return enc.Buf.Bytes(), nil
}

// NOTE: UnmarshalBEVE is not generated to avoid infinite recursion with beve.Unmarshal.
// Standard reflection-based beve.Unmarshal(data, &obj) should be used for decoding.
// Generated MarshalBEVE provides 10× performance improvement for encoding.
