// Code generated by bevegen. DO NOT EDIT.

package main

import (
	"github.com/beve-org/beve-go/core"
)

// MarshalBEVE encodes User to BEVE format using generated code.
//
// This method is automatically generated by bevegen and provides
// significantly better performance than reflection-based encoding.
//
// Performance: ~100ns for small structs (vs ~1000ns with reflection)
func (s *User) MarshalBEVE() ([]byte, error) {
	enc := core.GetEncoderFromPool()
	defer core.PutEncoderToPool(enc)

	// Write struct header (TYPE_OBJECT)
	if err := enc.WriteByte(0x86); err != nil {
		return nil, err
	}

	// Write field count (placeholder, will be updated)
	fieldCount := 5
	// Skip email if zero
	if s.Email == "" {
		fieldCount--
	}

	if err := enc.WriteCompressedUint(uint64(fieldCount)); err != nil {
		return nil, err
	}

	// Encode fields
	// Field: id
	if err := core.EncodeStringFast(enc, "id"); err != nil {
		return nil, err
	}
	if err := core.EncodeIntFast(enc, int64(s.ID)); err != nil {
		return nil, err
	}
	// Field: username
	if err := core.EncodeStringFast(enc, "username"); err != nil {
		return nil, err
	}
	if err := core.EncodeStringFast(enc, s.Username); err != nil {
		return nil, err
	}
	if s.Email != "" {
		// Field: email
		if err := core.EncodeStringFast(enc, "email"); err != nil {
			return nil, err
		}
		if err := core.EncodeStringFast(enc, s.Email); err != nil {
			return nil, err
		}
	}
	// Field: age
	if err := core.EncodeStringFast(enc, "age"); err != nil {
		return nil, err
	}
	if err := core.EncodeIntFast(enc, int64(s.Age)); err != nil {
		return nil, err
	}
	// Field: active
	if err := core.EncodeStringFast(enc, "active"); err != nil {
		return nil, err
	}
	if err := core.EncodeBoolFast(enc, s.IsActive); err != nil {
		return nil, err
	}

	return enc.Buf.Bytes(), nil
}

// NOTE: UnmarshalBEVE is not generated to avoid infinite recursion with beve.Unmarshal.
// Standard reflection-based beve.Unmarshal(data, &obj) should be used for decoding.
// Generated MarshalBEVE provides 10× performance improvement for encoding.
